<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'admin' })
const notice = ref('')
const running = ref(false)
const { data, refresh } = await useAsyncData('admin-jobs', () => $fetch('/api/admin/jobs'))
const bulkJobs = computed(() => (data.value?.items || []).filter((job: any) => String(job.type).includes('_bulk_action')))
const normalJobs = computed(() => (data.value?.items || []).filter((job: any) => !String(job.type).includes('_bulk_action')))
function parseError(error:any){return error?.data?.message||error?.data?.statusMessage||'操作失败'}
async function runPending(){running.value=true;notice.value='';try{await $fetch('/api/admin/jobs/run',{method:'POST',body:{type:'process_pending_submissions'}});notice.value='已触发批量处理任务';await refresh()}catch(error:any){notice.value=parseError(error)}finally{running.value=false}}
async function retry(jobId:string){if(!window.confirm('确认重试该失败任务？'))return;try{await $fetch(`/api/admin/jobs/${jobId}/retry`,{method:'POST'});notice.value='重试任务已创建';await refresh()}catch(error:any){notice.value=parseError(error)}}
</script>
<template><div class="space-y-6"><div class="flex flex-wrap items-end justify-between gap-4"><div><div class="label-overline">Jobs & automation</div><h1 class="text-3xl">任务日志与自动化</h1></div><button class="btn-primary" :disabled="running" @click="runPending">{{ running ? '执行中...' : '批量处理待审核提交' }}</button></div><p v-if="notice" class="text-sm" :class="notice.includes('失败') ? 'text-danger' : 'text-mint'">{{ notice }}</p><div class="space-y-4"><div class="panel p-5"><h2 class="text-xl">批量任务执行记录</h2><div class="mt-4 space-y-3"><div v-for="job in bulkJobs" :key="job.id" class="rounded-sm border border-charcoal p-3"><div class="flex flex-wrap items-start justify-between gap-4"><div><div class="font-medium">{{ job.type }}</div><div class="text-xs text-slate">{{ job.startedAtLabel }} -> {{ job.finishedAtLabel }}</div><p class="mt-2 text-sm text-parchment">{{ job.summary || '暂无摘要' }}</p></div><span class="badge" :class="job.status === 'success' ? 'text-mint' : job.status === 'failed' ? 'text-danger' : 'text-warning'">{{ job.status }}</span></div></div><div v-if="!bulkJobs.length" class="text-sm text-slate">暂无批量任务记录</div></div></div><div v-for="job in normalJobs" :key="job.id" class="panel p-5"><div class="flex flex-wrap items-start justify-between gap-4"><div><div class="text-lg font-semibold">{{ job.type }}</div><div class="mt-1 text-sm text-slate">{{ job.startedAtLabel }} -> {{ job.finishedAtLabel }}</div><p class="mt-3 text-sm text-parchment">{{ job.summary || '暂无摘要' }}</p></div><div class="flex items-center gap-3"><span class="badge" :class="job.status === 'success' ? 'text-mint' : job.status === 'failed' ? 'text-danger' : 'text-warning'">{{ job.status }}</span><button v-if="job.retryable" class="btn-ghost" @click="retry(job.id)">重试</button></div></div><pre v-if="job.log" class="mt-4 overflow-x-auto rounded-sm border border-charcoal bg-abyss p-4 text-xs text-parchment">{{ job.log }}</pre></div></div></div></template>
