<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: 'admin' })
const route = useRoute()
const notice = ref('')
const { data, refresh } = await useAsyncData(`admin-analysis-${route.params.id}`, () => $fetch(`/api/admin/analyses/${route.params.id}`))
const form = reactive({risk_level:'medium',one_liner:'',key_findings:['','',''],plain_summary:'',data_collected:[''],data_shared_with:[''],user_rights:[''],dispute:''})
watchEffect(()=>{const analysis=data.value?.app?.analysis;if(!analysis)return;Object.assign(form,{risk_level:analysis.risk_level||'medium',one_liner:analysis.one_liner||'',key_findings:[...(analysis.key_findings||[''])],plain_summary:analysis.plain_summary||'',data_collected:[...(analysis.data_collected||[''])],data_shared_with:[...(analysis.data_shared_with||[''])],user_rights:[...(analysis.user_rights||[''])],dispute:analysis.dispute||''})})
function normalizeList(values:string[]){return values.map((item)=>item.trim()).filter(Boolean)}
function parseError(error:any){return error?.data?.message||error?.data?.statusMessage||'操作失败'}
function containsDeterministicLegalTerms(){const text=[form.one_liner,form.plain_summary,form.dispute,...form.key_findings,...form.data_collected,...form.data_shared_with,...form.user_rights].join(' ');return text.includes('违法')||text.includes('非法')}
async function save(){if(containsDeterministicLegalTerms()){notice.value='请避免使用“违法/非法”等确定性表述，建议使用中性措辞。';return}try{await $fetch(`/api/admin/analyses/${route.params.id}`,{method:'PATCH',body:{...form,key_findings:normalizeList(form.key_findings),data_collected:normalizeList(form.data_collected),data_shared_with:normalizeList(form.data_shared_with),user_rights:normalizeList(form.user_rights)}});notice.value='保存成功';await refresh()}catch(error:any){notice.value=parseError(error)}}
async function restore(){if(!window.confirm('确认恢复 AI 初稿？'))return;try{await $fetch(`/api/admin/analyses/${route.params.id}/restore`,{method:'POST'});notice.value='已恢复到 AI 初始版本';await refresh()}catch(error:any){notice.value=parseError(error)}}
</script>
<template><div v-if="data?.app" class="space-y-6"><div class="flex flex-wrap items-end justify-between gap-4"><div><div class="label-overline">Analysis detail</div><h1 class="text-3xl">{{ data.app.name }} 分析编辑器</h1></div><div class="flex gap-3"><button class="btn-ghost" @click="restore">恢复 AI 初稿</button><button class="btn-primary" @click="save">保存分析</button></div></div><div class="grid gap-6 xl:grid-cols-[1.1fr,0.9fr]"><div class="panel p-5 space-y-4"><div class="grid gap-4 md:grid-cols-2"><select v-model="form.risk_level" class="select-base"><option value="low">low</option><option value="medium">medium</option><option value="high">high</option><option value="critical">critical</option></select><input v-model="form.one_liner" class="input-base" placeholder="一句话总结" /></div><textarea v-model="form.plain_summary" class="textarea-base" placeholder="白话摘要"></textarea><textarea v-model="form.dispute" class="textarea-base" placeholder="争议解决"></textarea><div><div class="mb-2 font-medium">关键发现</div><div class="space-y-2"><input v-for="(_, index) in form.key_findings" :key="index" v-model="form.key_findings[index]" class="input-base" :placeholder="`关键发现 ${index + 1}`" /><button class="btn-ghost" @click="form.key_findings.push('')">新增一条</button></div></div></div><div class="space-y-6"><div class="panel p-5"><div class="mb-2 font-medium">收集的数据</div><div class="space-y-2"><input v-for="(_, index) in form.data_collected" :key="`col-${index}`" v-model="form.data_collected[index]" class="input-base" /><button class="btn-ghost" @click="form.data_collected.push('')">新增</button></div></div><div class="panel p-5"><div class="mb-2 font-medium">共享对象</div><div class="space-y-2"><input v-for="(_, index) in form.data_shared_with" :key="`share-${index}`" v-model="form.data_shared_with[index]" class="input-base" /><button class="btn-ghost" @click="form.data_shared_with.push('')">新增</button></div></div><div class="panel p-5"><div class="mb-2 font-medium">用户权利</div><div class="space-y-2"><input v-for="(_, index) in form.user_rights" :key="`right-${index}`" v-model="form.user_rights[index]" class="input-base" /><button class="btn-ghost" @click="form.user_rights.push('')">新增</button></div></div></div></div><p class="text-sm" :class="notice.includes('失败') || notice.includes('避免') ? 'text-danger' : 'text-mint'">{{ notice }}</p></div></template>
